// @ts-nocheck
import { AutoAwesomeOutlined, PhotoCameraOutlined, PersonOutlineOutlined, SaveOutlined } from "@mui/icons-material";
import { Alert, Avatar, Box, Dialog, DialogActions, DialogContent, DialogTitle, Stack, TextField, Typography } from "@mui/material";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../../features/auth/AuthProvider";
import { apiAssetUrl } from "../../shared/api/apiClient";
import { AppButton } from "../../shared/ui/AppButton";
import { AppCard } from "../../shared/ui/AppCard";
import { PageHeader } from "../../shared/ui/PageHeader";

const DICEBEAR_STYLES = ["waves", "stack", "stripes", "initial-face", "patchwork"];
type AvatarSource = "none" | "upload" | "generated" | undefined;

export function ProfilePage() {
  const { user, updateProfile } = useAuth();
  const [displayName, setDisplayName] = useState(""); const [bio, setBio] = useState("");
  const [avatarSource, setAvatarSource] = useState<AvatarSource>(); const [avatarFile, setAvatarFile] = useState<File | null>(null); const [localPreview, setLocalPreview] = useState("");
  const [diceBearStyle, setDiceBearStyle] = useState("waves"); const [diceBearSeed, setDiceBearSeed] = useState(() => crypto.randomUUID().replaceAll("-", "")); const [gridSeed, setGridSeed] = useState(() => crypto.randomUUID().replaceAll("-", ""));
  const [avatarDialogOpen, setAvatarDialogOpen] = useState(false); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => () => { if (localPreview) URL.revokeObjectURL(localPreview); }, [localPreview]);
  useEffect(() => { setDisplayName(user?.profile.displayName ?? user?.username ?? ""); setBio(user?.profile.bio ?? ""); setAvatarSource(undefined); setAvatarFile(null); setLocalPreview(""); }, [user]);
  const generatedPreview = useMemo(() => `https://api.dicebear.com/10.x/${diceBearStyle}/svg?seed=${encodeURIComponent(diceBearSeed)}`, [diceBearSeed, diceBearStyle]);
  const avatarOptions = useMemo(() => Array.from({ length: 15 }, (_, index) => ({ style: DICEBEAR_STYLES[index % DICEBEAR_STYLES.length], seed: `${gridSeed}-${index}` })), [gridSeed]);
  if (!user) return null;
  const currentName = user.profile.displayName?.trim() || user.username;
  const preview = avatarSource === "upload" ? localPreview : avatarSource === "generated" ? generatedPreview : avatarSource === "none" ? "" : user.profile.avatar?.url ? apiAssetUrl(user.profile.avatar.url) : "";
  const isDirty = displayName !== (user.profile.displayName ?? user.username) || bio !== (user.profile.bio ?? "") || avatarSource !== undefined;
  function chooseLocalAvatar(file: File | null) { if (localPreview) URL.revokeObjectURL(localPreview); setAvatarFile(file); setLocalPreview(file ? URL.createObjectURL(file) : ""); if (file) setAvatarSource("upload"); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!isDirty) return; setSaving(true); setError(""); try { const data = new FormData(); if (displayName !== (user.profile.displayName ?? user.username)) data.set("displayName", displayName); if (bio !== (user.profile.bio ?? "")) data.set("bio", bio); if (avatarSource) { data.set("avatarSource", avatarSource); if (avatarSource === "upload" && avatarFile) data.set("avatar", avatarFile); if (avatarSource === "generated") { data.set("diceBearStyle", diceBearStyle); data.set("diceBearSeed", diceBearSeed); } } await updateProfile(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudieron guardar los cambios."); } finally { setSaving(false); } }
  return <Box component="main" className="profile-shell"><PageHeader eyebrow="Cuenta" title="Tu perfil." description="Personalizá cómo aparecés dentro de Motion Analysis." action={<AppButton component={Link} to="/" variant="outlined">Volver a la biblioteca</AppButton>} />
    <AppCard component="section" className="profile-card" sx={{ p: { xs: 2, sm: 4 } }}><Stack className="profile-avatar-section" direction={{ xs: "column", sm: "row" }} alignItems="center" gap={2}><Avatar src={preview || undefined} sx={{ width: 88, height: 88, bgcolor: "primary.main", fontSize: 28, fontWeight: 800 }}>{preview ? null : currentName.slice(0, 1).toUpperCase()}</Avatar><Box flex={1}><Typography variant="overline" color="primary.main" fontWeight={800}>Imagen de perfil</Typography><Typography variant="h5">{currentName}</Typography><Typography color="text.secondary" variant="body2">Elegí una imagen local, un avatar generado o usá tus iniciales.</Typography><Stack direction="row" flexWrap="wrap" gap={1} mt={1.5}><AppButton component="label" size="small" variant="outlined" startIcon={<PhotoCameraOutlined />}>Subir imagen<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => chooseLocalAvatar(event.target.files?.[0] ?? null)} /></AppButton><AppButton type="button" size="small" variant="outlined" startIcon={<AutoAwesomeOutlined />} onClick={() => setAvatarDialogOpen(true)}>Elegir avatar</AppButton><AppButton type="button" size="small" variant="text" startIcon={<PersonOutlineOutlined />} onClick={() => { setAvatarSource("none"); setAvatarFile(null); setLocalPreview(""); }}>Usar iniciales</AppButton></Stack></Box></Stack>
      <Box component="form" className="profile-form" onSubmit={submit}><Typography variant="h5">Información pública</Typography><TextField label="Nombre visible" value={displayName} inputProps={{ maxLength: 80 }} onChange={(event) => setDisplayName(event.target.value)} /><TextField label="Bio" value={bio} inputProps={{ maxLength: 280 }} multiline minRows={4} onChange={(event) => setBio(event.target.value)} helperText={`${bio.length}/280`} />{error && <Alert severity="error">{error}</Alert>}<AppButton type="submit" disabled={!isDirty || saving} startIcon={<SaveOutlined />}>{saving ? "Guardando..." : "Guardar cambios"}</AppButton></Box>
      <Box className="profile-account-data"><Typography variant="h5">Datos de cuenta</Typography><Stack gap={1.25} mt={2}><Typography variant="body2"><strong>Email</strong><br />{user.email}</Typography><Typography variant="body2"><strong>Usuario</strong><br />@{user.username}</Typography><Typography variant="body2"><strong>Plan</strong><br />{user.role}</Typography></Stack></Box></AppCard>
    <Dialog open={avatarDialogOpen} onClose={() => setAvatarDialogOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Elegí un avatar</DialogTitle><DialogContent><Typography color="text.secondary" variant="body2" mb={2}>Elegí una opción generada o creá una nueva grilla.</Typography><Box className="avatar-grid">{avatarOptions.map((option) => <AppButton key={`${option.style}-${option.seed}`} variant="outlined" sx={{ p: 0.5, minWidth: 0 }} onClick={() => { setDiceBearStyle(option.style); setDiceBearSeed(option.seed); setAvatarSource("generated"); setAvatarDialogOpen(false); }}><img src={`https://api.dicebear.com/10.x/${option.style}/svg?seed=${encodeURIComponent(option.seed)}`} alt={`Avatar ${option.style}`} /></AppButton>)}</Box></DialogContent><DialogActions><AppButton variant="text" onClick={() => setGridSeed(crypto.randomUUID().replaceAll("-", ""))}>Generar opciones</AppButton><AppButton onClick={() => setAvatarDialogOpen(false)}>Listo</AppButton></DialogActions></Dialog></Box>;
}
